/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApplicationStatusDisplay: typeof import('./components/bewerbungen/ApplicationStatusDisplay.vue')['default']
    ApplicationStatusText: typeof import('./components/textbrackets/ApplicationStatusText.vue')['default']
    BaseButtonApplication: typeof import('./components/common/BaseButtonApplication.vue')['default']
    BaseButtonCancel: typeof import('./components/common/BaseButtonCancel.vue')['default']
    BaseButtonEdit: typeof import('./components/common/BaseButtonEdit.vue')['default']
    BaseButtonLogin: typeof import('./components/common/BaseButtonLogin.vue')['default']
    BaseButtonLogout: typeof import('./components/common/BaseButtonLogout.vue')['default']
    BaseButtonMarkJob: typeof import('./components/common/BaseButtonMarkJob.vue')['default']
    BaseButtonVerify: typeof import('./components/common/BaseButtonVerify.vue')['default']
    BaseCardApplicationMini: typeof import('./components/bewerbungen/BaseCardApplicationMini.vue')['default']
    BaseCardApplicationProcess: typeof import('./components/bewerbungen/BaseCardApplicationProcess.vue')['default']
    BaseCardJobMini: typeof import('./components/stellen/BaseCardJobMini.vue')['default']
    BaseCardMarkJob: typeof import('./components/stellen/BaseCardMarkJob.vue')['default']
    BaseCardNwkDocuments: typeof import('./components/nachwuchskraefte/BaseCardNwkDocuments.vue')['default']
    BaseCardNwkExperienceAndInterests: typeof import('./components/nachwuchskraefte/BaseCardNwkExperienceAndInterests.vue')['default']
    BaseCardNwkPersonal: typeof import('./components/nachwuchskraefte/BaseCardNwkPersonal.vue')['default']
    BaseDialogApplication: typeof import('./components/bewerbungen/BaseDialogApplication.vue')['default']
    BaseDialogMessage: typeof import('./components/bewerbungen/BaseDialogMessage.vue')['default']
    BaseDialogNwkUpdateExperienceAndInterests: typeof import('./components/nachwuchskraefte/BaseDialogNwkUpdateExperienceAndInterests.vue')['default']
    BaseDialogNwkUploadDocuments: typeof import('./components/nachwuchskraefte/BaseDialogNwkUploadDocuments.vue')['default']
    DashboardCard: typeof import('./components/textbrackets/DashboardCard.vue')['default']
    JobCard: typeof import('./components/stellen/JobCard.vue')['default']
    JobMatchScore: typeof import('./components/stellen/JobMatchScore.vue')['default']
    MatchingJobText: typeof import('./components/textbrackets/MatchingJobText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
