/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApplicationButton: typeof import('./components/ApplicationButton.vue')['default']
    ApplicationDialog: typeof import('./components/bewerbungen/ApplicationDialog.vue')['default']
    ApplicationStatusDisplay: typeof import('./components/bewerbungen/ApplicationStatusDisplay.vue')['default']
    ApplicationStatusText: typeof import('./components/textbrackets/ApplicationStatusText.vue')['default']
    BaseApplicationButton: typeof import('./components/common/BaseApplicationButton.vue')['default']
    BaseButtonApplication: typeof import('./components/common/BaseButtonApplication.vue')['default']
    BaseButtonCancel: typeof import('./components/common/BaseButtonCancel.vue')['default']
    BaseButtonEdit: typeof import('./components/common/BaseButtonEdit.vue')['default']
    BaseButtonLogin: typeof import('./components/common/BaseButtonLogin.vue')['default']
    BaseButtonLogout: typeof import('./components/common/BaseButtonLogout.vue')['default']
    BaseButtonMarkJob: typeof import('./components/common/BaseButtonMarkJob.vue')['default']
    BaseButtonVerify: typeof import('./components/common/BaseButtonVerify.vue')['default']
    BaseCancelButton: typeof import('./components/common/BaseCancelButton.vue')['default']
    BaseCardApplicationProcess: typeof import('./components/bewerbungen/BaseCardApplicationProcess.vue')['default']
    BaseCardNwkPersonal: typeof import('./components/nachwuchskraefte/BaseCardNwkPersonal.vue')['default']
    BaseDialogApplication: typeof import('./components/bewerbungen/BaseDialogApplication.vue')['default']
    BaseDialogMessage: typeof import('./components/bewerbungen/BaseDialogMessage.vue')['default']
    BaseEditButton: typeof import('./components/common/BaseEditButton.vue')['default']
    BaseVerifyButton: typeof import('./components/common/BaseVerifyButton.vue')['default']
    DashboardCard: typeof import('./components/textbrackets/DashboardCard.vue')['default']
    JobCard: typeof import('./components/stellen/JobCard.vue')['default']
    JobMatchScore: typeof import('./components/stellen/JobMatchScore.vue')['default']
    MatchingJobText: typeof import('./components/textbrackets/MatchingJobText.vue')['default']
    NotAktive_BaseDialogNwkUpdatePersonal: typeof import('./components/nachwuchskraefte/NotAktive_BaseDialogNwkUpdatePersonal.vue')['default']
    NotAktive_NwkUpdateProfileDialog: typeof import('./components/nachwuchskraefte/NotAktive_NwkUpdateProfileDialog.vue')['default']
    NwkDocumentsCard: typeof import('./components/nachwuchskraefte/NwkDocumentsCard.vue')['default']
    NwkExperienceAndInterestsCard: typeof import('./components/nachwuchskraefte/NwkExperienceAndInterestsCard.vue')['default']
    NwkProfileCard: typeof import('./components/nachwuchskraefte/NwkProfileCard.vue')['default']
    NwkUpdateExpierenceAndIntrestsDialog: typeof import('./components/nachwuchskraefte/NwkUpdateExpierenceAndIntrestsDialog.vue')['default']
    NwkUpdateProfileDialog: typeof import('./components/nachwuchskraefte/NwkUpdateProfileDialog.vue')['default']
    NwkUploadDocumentsDialog: typeof import('./components/nachwuchskraefte/NwkUploadDocumentsDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
