/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/bewerbungen/[id]/ApplicationView': RouteRecordInfo<'/bewerbungen/[id]/ApplicationView', '/bewerbungen/:id/ApplicationView', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/bewerbungen/ApplicationListView': RouteRecordInfo<'/bewerbungen/ApplicationListView', '/bewerbungen/ApplicationListView', Record<never, never>, Record<never, never>>,
    '/LoginView': RouteRecordInfo<'/LoginView', '/LoginView', Record<never, never>, Record<never, never>>,
    '/merken/BookmarkView': RouteRecordInfo<'/merken/BookmarkView', '/merken/BookmarkView', Record<never, never>, Record<never, never>>,
    '/nachwuchskraefte/NwkUserinformationView': RouteRecordInfo<'/nachwuchskraefte/NwkUserinformationView', '/nachwuchskraefte/NwkUserinformationView', Record<never, never>, Record<never, never>>,
    '/stellen/[id]/JobpostingTemplateView': RouteRecordInfo<'/stellen/[id]/JobpostingTemplateView', '/stellen/:id/JobpostingTemplateView', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/stellen/JobpostingOverviewView': RouteRecordInfo<'/stellen/JobpostingOverviewView', '/stellen/JobpostingOverviewView', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/bewerbungen/[id]/ApplicationView.vue': {
      routes: '/bewerbungen/[id]/ApplicationView'
      views: never
    }
    'src/pages/bewerbungen/ApplicationListView.vue': {
      routes: '/bewerbungen/ApplicationListView'
      views: never
    }
    'src/pages/LoginView.vue': {
      routes: '/LoginView'
      views: never
    }
    'src/pages/merken/BookmarkView.vue': {
      routes: '/merken/BookmarkView'
      views: never
    }
    'src/pages/nachwuchskraefte/NwkUserinformationView.vue': {
      routes: '/nachwuchskraefte/NwkUserinformationView'
      views: never
    }
    'src/pages/stellen/[id]/JobpostingTemplateView.vue': {
      routes: '/stellen/[id]/JobpostingTemplateView'
      views: never
    }
    'src/pages/stellen/JobpostingOverviewView.vue': {
      routes: '/stellen/JobpostingOverviewView'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
