/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApplicationDialog: typeof import('./components/stellen/ApplicationDialog.vue')['default']
    ApplicationStatusDisplay: typeof import('./components/bewerbungen/ApplicationStatusDisplay.vue')['default']
    ApplicationStatusText: typeof import('./components/textbrackets/ApplicationStatusText.vue')['default']
    DashboardCard: typeof import('./components/textbrackets/DashboardCard.vue')['default']
    JobCard: typeof import('./components/stellen/JobCard.vue')['default']
    JobMatchScore: typeof import('./components/stellen/JobMatchScore.vue')['default']
    MatchingJobText: typeof import('./components/textbrackets/MatchingJobText.vue')['default']
    NwkDocumentsCard: typeof import('./components/nachwuchskraefte/NwkDocumentsCard.vue')['default']
    NwkExperienceAndInterestsCard: typeof import('./components/nachwuchskraefte/NwkExperienceAndInterestsCard.vue')['default']
    NwkProfileCard: typeof import('./components/nachwuchskraefte/NwkProfileCard.vue')['default']
    NwkUpdateExpierenceAndIntrestsDialog: typeof import('./components/nachwuchskraefte/NwkUpdateExpierenceAndIntrestsDialog.vue')['default']
    NwkUpdateProfileDialog: typeof import('./components/nachwuchskraefte/NwkUpdateProfileDialog.vue')['default']
    NwkUploadDocumentsDialog: typeof import('./components/nachwuchskraefte/NwkUploadDocumentsDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
