/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApplicationStatusDisplay: typeof import('./components/bewerbungen/ApplicationStatusDisplay.vue')['default']
    JobCard: typeof import('./components/stellen/JobCard.vue')['default']
    NwkCard: typeof import('./components/nachwuchskraefte/NwkCard.vue')['default']
    NwkUpdateDialog: typeof import('./components/nachwuchskraefte/NwkUpdateDialog.vue')['default']
    NwkUploadDocumentsDialog: typeof import('./components/nachwuchskraefte/NwkUploadDocumentsDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
