/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/bewerbungen/ApplicationView': RouteRecordInfo<'/bewerbungen/ApplicationView', '/bewerbungen/ApplicationView', Record<never, never>, Record<never, never>>,
    '/nachwuchskraefte/NwkBookmarkView': RouteRecordInfo<'/nachwuchskraefte/NwkBookmarkView', '/nachwuchskraefte/NwkBookmarkView', Record<never, never>, Record<never, never>>,
    '/nachwuchskraefte/NwkUserinformationView': RouteRecordInfo<'/nachwuchskraefte/NwkUserinformationView', '/nachwuchskraefte/NwkUserinformationView', Record<never, never>, Record<never, never>>,
    '/stellen/JobDisplayVorlage': RouteRecordInfo<'/stellen/JobDisplayVorlage', '/stellen/JobDisplayVorlage', Record<never, never>, Record<never, never>>,
    '/stellen/JobDisplayVorlage2': RouteRecordInfo<'/stellen/JobDisplayVorlage2', '/stellen/JobDisplayVorlage2', Record<never, never>, Record<never, never>>,
    '/stellen/JobpostingView': RouteRecordInfo<'/stellen/JobpostingView', '/stellen/JobpostingView', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/bewerbungen/ApplicationView.vue': {
      routes: '/bewerbungen/ApplicationView'
      views: never
    }
    'src/pages/nachwuchskraefte/NwkBookmarkView.vue': {
      routes: '/nachwuchskraefte/NwkBookmarkView'
      views: never
    }
    'src/pages/nachwuchskraefte/NwkUserinformationView.vue': {
      routes: '/nachwuchskraefte/NwkUserinformationView'
      views: never
    }
    'src/pages/stellen/JobDisplayVorlage.vue': {
      routes: '/stellen/JobDisplayVorlage'
      views: never
    }
    'src/pages/stellen/JobDisplayVorlage2.vue': {
      routes: '/stellen/JobDisplayVorlage2'
      views: never
    }
    'src/pages/stellen/JobpostingView.vue': {
      routes: '/stellen/JobpostingView'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
